In [2]:
from itertools import permutations
import numpy as np
import math
import time
import pandas as pd

In [3]:
def removeFromArray(baseArray, searchArray):
    for index in range(len(baseArray)):
        if np.array_equal(baseArray[index], searchArray):
            return np.delete(baseArray, index, 0)

    raise ValueError(f'{searchArray} not in base array')

In [4]:
def megaArrayComparison(baseArray, comparisonArray, numberOfElements):
  countOfInstances = 0

  for index in range(len(baseArray)-numberOfElements+1):
    if np.array_equal(baseArray[index:numberOfElements+index], comparisonArray):
      countOfInstances += 1

  return countOfInstances

In [5]:
def reversedComparison(posibleArray, comparisonArray, numberOfElements):
  falsePerms = []

  for index in range(len(comparisonArray)-numberOfElements+1):
    currentPerm = comparisonArray[index:numberOfElements+index]
    found = False

    for perm in posibleArray:
      if np.array_equal(currentPerm, perm):
        found = True
        break

    if found == False:
      falsePerms.append(currentPerm)

  return falsePerms

In [6]:
def superPermutN (nElements, startingElement, initialPermutations, stepPrint, take):

  n = nElements
  ArrProb = initialPermutations
  ArrCheck = []

  suPP = startingElement
  ArrCheck.append(startingElement)
  ArrProb = removeFromArray(ArrProb, startingElement)
  steps = 1

  while len(ArrProb) != 0:
    steps += 1
    i = 1
    filter = ArrProb[np.sum(ArrProb[:,:(n-i)] == suPP[-(n-i):], axis=1) == (n - i)]

    while len(filter) == 0:
      i += 1
      filter = ArrProb[np.sum(ArrProb[:,:(n-i)] == suPP[-(n-i):], axis=1) == (n - i)]

    suPP = np.append(suPP,filter[take][-i:], axis=0)
    ArrCheck.append(filter[take])
    ArrProb = removeFromArray(ArrProb, filter[take])

    if stepPrint:
      print(f'Step {steps}:  {suPP}')

  lbn = math.factorial(n) + math.factorial(n - 1) + math.factorial(n - 2) + (n - 3)

  return [ArrCheck[0], len(suPP), steps, suPP]

In [8]:
start_time = time.time()
n = 4
posiblePs = np.array(list(permutations(range(1, n+1))))
tempPerm = superPermutN(n, posiblePs[7], posiblePs, True, 0)

lbn = math.factorial(n) + math.factorial(n - 1) + math.factorial(n - 2) + (n - 3)

print(f'number of elements: {n}')
print(f'Theoretical lower bound: {lbn}')
print('-'*80)
print(f'Lenght of Answer: {tempPerm[1]}')
print(f'Number of steps: {tempPerm[2]}')
print(f'Full Answer: {tempPerm[3]}')
print("--- %s seconds ---" % (time.time() - start_time))


Step 2:  [2 1 4 3 2]
Step 3:  [2 1 4 3 2 1]
Step 4:  [2 1 4 3 2 1 4]
Step 5:  [2 1 4 3 2 1 4 2 3]
Step 6:  [2 1 4 3 2 1 4 2 3 1]
Step 7:  [2 1 4 3 2 1 4 2 3 1 4]
Step 8:  [2 1 4 3 2 1 4 2 3 1 4 2]
Step 9:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3]
Step 10:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4]
Step 11:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4 2]
Step 12:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4 2 1]
Step 13:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4 2 1 2 3 4]
Step 14:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4 2 1 2 3 4 1]
Step 15:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4 2 1 2 3 4 1 2]
Step 16:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4 2 1 2 3 4 1 2 3]
Step 17:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4 2 1 2 3 4 1 2 3 1 2 4]
Step 18:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4 2 1 2 3 4 1 2 3 1 2 4 3]
Step 19:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4 2 1 2 3 4 1 2 3 1 2 4 3 1]
Step 20:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4 2 1 2 3 4 1 2 3 1 2 4 3 1 2]
Step 21:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4 2 1 2 3 4 1 2 3 1 2 4 3 1 2 4 1 3]
Step 22:  [2 1 4 3 2 1 4 2 3 1 4 2 1 3 4 2 1 2 3 4 1 2 3 1 2 4 3 1 2

In [9]:
n = 4
posiblePs = np.array(list(permutations(range(1, n+1))))

dfTemp = pd.DataFrame(columns=['Starting', 'Lenght', 'Steps', 'Answer'])
currRow = 0

lbn = math.factorial(n) + math.factorial(n - 1) + math.factorial(n - 2) + (n - 3)

print(f'Theoretical lower bound: {lbn} \n')

for currPermutation in posiblePs:
  tempPerm = superPermutN(n, currPermutation, posiblePs, False, 0)
  tempRow = []
  tempRow.append(tempPerm[0])
  tempRow.append(tempPerm[1])
  tempRow.append(tempPerm[2])
  tempRow.append(tempPerm[3])
  dfTemp.loc[currRow] = tempRow
  currRow += 1

dfTemp

Theoretical lower bound: 33 



Starting  Lenght  Steps  \
0   [1, 2, 3, 4]      33     24   
1   [1, 2, 4, 3]      34     24   
2   [1, 3, 2, 4]      33     24   
3   [1, 3, 4, 2]      34     24   
4   [1, 4, 2, 3]      33     24   
5   [1, 4, 3, 2]      34     24   
6   [2, 1, 3, 4]      33     24   
7   [2, 1, 4, 3]      35     24   
8   [2, 3, 1, 4]      33     24   
9   [2, 3, 4, 1]      35     24   
10  [2, 4, 1, 3]      33     24   
11  [2, 4, 3, 1]      35     24   
12  [3, 1, 2, 4]      33     24   
13  [3, 1, 4, 2]      35     24   
14  [3, 2, 1, 4]      33     24   
15  [3, 2, 4, 1]      35     24   
16  [3, 4, 1, 2]      35     24   
17  [3, 4, 2, 1]      35     24   
18  [4, 1, 2, 3]      35     24   
19  [4, 1, 3, 2]      35     24   
20  [4, 2, 1, 3]      35     24   
21  [4, 2, 3, 1]      35     24   
22  [4, 3, 1, 2]      35     24   
23  [4, 3, 2, 1]      35     24   

                                               Answer  
0   [1, 2, 3, 4, 1, 2, 3, 1, 4, 2, 3, 1, 2, 4, 3, ...  
1   [1, 2, 4, 3, 1, 2, 4, 1, 3, 2, 4, 1, 2, 3, 4, ...  
2   [1, 3, 2, 4, 1, 3, 2, 1, 4, 3, 2, 1, 3, 4, 2, ...  
3   [1, 3, 4, 2, 1, 3, 4, 1, 2, 3, 4, 1, 3, 2, 4, ...  
4   [1, 4, 2, 3, 1, 4, 2, 1, 3, 4, 2, 1, 4, 3, 2, ...  
5   [1, 4, 3, 2, 1, 4, 3, 1, 2, 4, 3, 1, 4, 2, 3, ...  
6   [2, 1, 3, 4, 2, 1, 3, 2, 4, 1, 3, 2, 1, 4, 3, ...  
7   [2, 1, 4, 3, 2, 1, 4, 2, 3, 1, 4, 2, 1, 3, 4, ...  
8   [2, 3, 1, 4, 2, 3, 1, 2, 4, 3, 1, 2, 3, 4, 1, ...  
9   [2, 3, 4, 1, 2, 3, 4, 2, 1, 3, 4, 2, 3, 1, 4, ...  
10  [2, 4, 1, 3, 2, 4, 1, 2, 3, 4, 1, 2, 4, 3, 1, ...  
11  [2, 4, 3, 1, 2, 4, 3, 2, 1, 4, 3, 2, 4, 1, 3, ...  
12  [3, 1, 2, 4, 3, 1, 2, 3, 4, 1, 2, 3, 1, 4, 2, ...  
13  [3, 1, 4, 2, 3, 1, 4, 3, 2, 1, 4, 3, 1, 2, 4, ...  
14  [3, 2, 1, 4, 3, 2, 1, 3, 4, 2, 1, 3, 2, 4, 1, ...  
15  [3, 2, 4, 1, 3, 2, 4, 3, 1, 2, 4, 3, 2, 1, 4, ...  
16  [3, 4, 1, 2, 3, 4, 1, 3, 2, 4, 1, 3, 4, 2, 1, ...  
17  [3, 4, 2, 1, 3, 4, 2, 3, 1, 4, 2, 3, 4, 1, 2, ...  
18  [4, 1, 2, 3, 4, 1, 2, 4, 3, 1, 2, 4, 1, 3, 2, ...  
19  [4, 1, 3, 2, 4, 1, 3, 4, 2, 1, 3, 4, 1, 2, 3, ...  
20  [4, 2, 1, 3, 4, 2, 1, 4, 3, 2, 1, 4, 2, 3, 1, ...  
21  [4, 2, 3, 1, 4, 2, 3, 4, 1, 2, 3, 4, 2, 1, 3, ...  
22  [4, 3, 1, 2, 4, 3, 1, 4, 2, 3, 1, 4, 3, 2, 1, ...  
23  [4, 3, 2, 1, 4, 3, 2, 4, 1, 3, 2, 4, 3, 1, 2, ...

In [11]:
for perm in posiblePs:
  print(f'permutation {perm} was found {megaArrayComparison(tempPerm[3], perm, n)} times')

permutation [1 2 3 4] was found 1 times
permutation [1 2 4 3] was found 1 times
permutation [1 3 2 4] was found 1 times
permutation [1 3 4 2] was found 1 times
permutation [1 4 2 3] was found 1 times
permutation [1 4 3 2] was found 1 times
permutation [2 1 3 4] was found 1 times
permutation [2 1 4 3] was found 1 times
permutation [2 3 1 4] was found 1 times
permutation [2 3 4 1] was found 1 times
permutation [2 4 1 3] was found 1 times
permutation [2 4 3 1] was found 2 times
permutation [3 1 2 4] was found 1 times
permutation [3 1 4 2] was found 1 times
permutation [3 2 1 4] was found 1 times
permutation [3 2 4 1] was found 1 times
permutation [3 4 1 2] was found 1 times
permutation [3 4 2 1] was found 1 times
permutation [4 1 2 3] was found 1 times
permutation [4 1 3 2] was found 1 times
permutation [4 2 1 3] was found 1 times
permutation [4 2 3 1] was found 1 times
permutation [4 3 1 2] was found 1 times
permutation [4 3 2 1] was found 1 times


In [12]:
reversedComparison(posiblePs, tempPerm[3], n)

[array([4, 3, 2, 4]),
 array([3, 2, 4, 3]),
 array([4, 3, 1, 4]),
 array([3, 1, 4, 1]),
 array([1, 4, 1, 2]),
 array([4, 1, 2, 1]),
 array([1, 2, 1, 3])]